version: "3.9"

services:

  app:
    build:
      context: .
      target: runtime
    container_name: spring-app

    ports:
      - "${SERVER_PORT}:8080"

    env_file:
      - .env

    depends_on:
      - mysql
      - redis

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

    restart: unless-stopped


  mysql:
    image: mysql:8.4
    container_name: mysql

    ports:
      - "${MYSQL_PORT}:3306"

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql-data:/var/lib/mysql

    restart: unless-stopped


  redis:
    image: redis:latest
    container_name: redis

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - redis-data:/data

    restart: unless-stopped


volumes:
  mysql-data:
  redis-data: